spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    client-id: moebius
    consumer:
      client-id: moebius-consumer
      auto-offset-reset: latest
      group-id: moebius-consumer