spring:
  profiles:
    active: prod
  kafka:
    bootstrap-servers: kafka.hashmainpro.com:9092
    client-id: moebius
    consumer:
      client-id: moebius-consumer
      auto-offset-reset: latest
      group-id: moebius-consumer
    jaas:
      login-module: org.apache.kafka.common.security.plain.PlainLoginModule
      options:
        username: moebius
        password: VVbRzWYK4OHE
      enabled: true
redis:
  master-server: 3.34.178.137
  master-port: 6379